/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemapersonalmunicipal.view;
import com.mycompany.sistemapersonalmunicipal.dao.AsistenciaDAO;
import java.time.LocalDate;

/**
 *
 * @author marantonio55
 */
public class FrmAsistencias extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAsistencias.class.getName());

    /**
     * Creates new form FrmAsistencias
     */
    public FrmAsistencias() {
        initComponents();
        setDefaultCloseOperation(
            javax.swing.WindowConstants.DISPOSE_ON_CLOSE
        );
        txtFecha.setText(
        LocalDate.now().toString()
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTipoTrabajador = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrarAsistencia = new javax.swing.JButton();
        txtDocumento = new javax.swing.JTextField();
        btnVerAsistencias = new javax.swing.JButton();
        btnBuscarTrabajador = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        txtTrabajador = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoTrabajador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHoraIngreso = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtHoraSalida = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaListado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTipoTrabajador.setEditable(false);

        jLabel6.setText("Hora ingreso:");

        jLabel1.setText("REGISTRO DE ASISTENCIAS");

        txtFecha.setEditable(false);

        jLabel2.setText("Documento:");

        btnRegistrarAsistencia.setText("Registrar Asistencia");
        btnRegistrarAsistencia.addActionListener(this::btnRegistrarAsistenciaActionPerformed);

        btnVerAsistencias.setText("Ver Asistencias");
        btnVerAsistencias.addActionListener(this::btnVerAsistenciasActionPerformed);

        btnBuscarTrabajador.setText("Buscar Trabajador");
        btnBuscarTrabajador.addActionListener(this::btnBuscarTrabajadorActionPerformed);

        jLabel3.setText("Trabajador:");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        txtTrabajador.setEditable(false);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        jLabel4.setText("Código :");

        txtCodigoTrabajador.setEditable(false);

        jLabel5.setText("Tipo:");

        jLabel7.setText("Fecha :");

        jLabel8.setText("Hora Salida:");

        txtAreaListado.setColumns(20);
        txtAreaListado.setRows(5);
        jScrollPane1.setViewportView(txtAreaListado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(btnBuscarTrabajador))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnLimpiar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnCerrar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHoraIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCodigoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTipoTrabajador))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrarAsistencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVerAsistencias)
                                .addGap(42, 42, 42)))))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarTrabajador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCodigoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtTipoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHoraIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarAsistencia)
                    .addComponent(btnVerAsistencias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCerrar))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAsistenciaActionPerformed
        // TODO add your handling code here:
        String documento =
                txtDocumento.getText().trim();

        String trabajador =
                txtTrabajador.getText().trim();

        String fecha =
                txtFecha.getText().trim();

        String horaIngreso =
                txtHoraIngreso.getText().trim();

        String horaSalida =
                txtHoraSalida.getText().trim();


        // 1. VALIDAR TRABAJADOR BUSCADO

        if (documento.isEmpty()
                || trabajador.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Primero debe buscar un trabajador válido."
            );

            txtDocumento.requestFocus();

            return;
        }


        // 2. VALIDAR FECHA

        if (fecha.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese la fecha de asistencia."
            );

            txtFecha.requestFocus();

            return;
        }


        // 3. VALIDAR HORA DE INGRESO

        if (horaIngreso.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese la hora de ingreso."
            );

            txtHoraIngreso.requestFocus();

            return;
        }


        // 4. VALIDAR HORA DE SALIDA

        if (horaSalida.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese la hora de salida."
            );

            txtHoraSalida.requestFocus();

            return;
        }


        // 5. REGISTRAR

        AsistenciaDAO asistenciaDAO =
                new AsistenciaDAO();

        try {

            boolean registrada =
                    asistenciaDAO.registrar(
                            documento,
                            fecha,
                            horaIngreso,
                            horaSalida
                    );

            if (registrada) {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Asistencia registrada correctamente."
                );

            } else {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "No se pudo registrar la asistencia.",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                );
            }

        } catch (IllegalArgumentException e) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Error: " + e.getMessage()
            );
        }
    }//GEN-LAST:event_btnRegistrarAsistenciaActionPerformed

    private void btnVerAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAsistenciasActionPerformed
        // TODO add your handling code here:
                String documento =
                txtDocumento.getText().trim();

        String trabajador =
                txtTrabajador.getText().trim();


        // VALIDAR QUE PRIMERO SE HAYA BUSCADO AL TRABAJADOR

        if (documento.isEmpty()
                || trabajador.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Primero debe buscar un trabajador."
            );

            txtDocumento.requestFocus();

            return;
        }


        AsistenciaDAO asistenciaDAO =
                new AsistenciaDAO();

        java.util.List<Object[]> lista =
                asistenciaDAO.listarPorDocumento(
                        documento
                );


        if (lista.isEmpty()) {

            txtAreaListado.setText(
                    "El trabajador no tiene asistencias registradas."
            );

            return;
        }


        StringBuilder texto =
                new StringBuilder();

        texto.append("HISTORIAL DE ASISTENCIAS\n");

        texto.append("Trabajador: ")
                .append(txtTrabajador.getText())
                .append("\n");

        texto.append("Código: ")
                .append(txtCodigoTrabajador.getText())
                .append("\n");

        texto.append("============================================\n\n");


        for (Object[] fila : lista) {

            texto.append("ID asistencia: ")
                    .append(fila[0])
                    .append("\n");

            texto.append("Fecha: ")
                    .append(fila[1])
                    .append("\n");

            texto.append("Hora ingreso: ")
                    .append(fila[2])
                    .append("\n");

            texto.append("Hora salida: ")
                    .append(fila[3])
                    .append("\n");

            texto.append("Tardanza: ");

            boolean tardanza =
                    (boolean) fila[4];

            if (tardanza) {

                texto.append("SÍ");

            } else {

                texto.append("NO");
            }

            texto.append("\n");

            texto.append(
                    "--------------------------------------------\n\n"
            );
        }


        txtAreaListado.setText(
                texto.toString()
        );

    }//GEN-LAST:event_btnVerAsistenciasActionPerformed

    private void btnBuscarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTrabajadorActionPerformed
        // TODO add your handling code here:
        String documento = txtDocumento.getText().trim();

        if (documento.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese el número de documento."
            );

            txtDocumento.requestFocus();

            return;
        }


        AsistenciaDAO asistenciaDAO =
                new AsistenciaDAO();

        Object[] trabajador =
                asistenciaDAO.buscarTrabajadorPorDocumento(
                        documento
                );


        if (trabajador == null) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "No se encontró un trabajador activo con ese documento."
            );

            txtTrabajador.setText("");
            txtCodigoTrabajador.setText("");
            txtTipoTrabajador.setText("");

            return;
        }


        // CARGAR DATOS DEL TRABAJADOR

        txtCodigoTrabajador.setText(
                trabajador[1].toString()
        );

        txtTrabajador.setText(
                trabajador[2].toString()
        );

        txtTipoTrabajador.setText(
                trabajador[3].toString()
        );
    }//GEN-LAST:event_btnBuscarTrabajadorActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtDocumento.setText("");
        txtTrabajador.setText("");
        txtCodigoTrabajador.setText("");
        txtTipoTrabajador.setText("");

        txtHoraIngreso.setText("");
        txtHoraSalida.setText("");

        txtAreaListado.setText("");

        txtFecha.setText(
                java.time.LocalDate.now().toString()
        );

        txtDocumento.requestFocus();

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAsistencias().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarTrabajador;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrarAsistencia;
    private javax.swing.JButton btnVerAsistencias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaListado;
    private javax.swing.JTextField txtCodigoTrabajador;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHoraIngreso;
    private javax.swing.JTextField txtHoraSalida;
    private javax.swing.JTextField txtTipoTrabajador;
    private javax.swing.JTextField txtTrabajador;
    // End of variables declaration//GEN-END:variables
}
