/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemapersonalmunicipal.view;

import com.mycompany.sistemapersonalmunicipal.dao.ContratoDAO;

/**
 *
 * @author marantonio55
 */
public class FrmGestionContratos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmGestionContratos.class.getName());

    /**
     * Creates new form FrmGestionContratos
     */
    public FrmGestionContratos() {
        initComponents();
        setDefaultCloseOperation(

            javax.swing.WindowConstants.DISPOSE_ON_CLOSE

    );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtTrabajador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoContrato = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("GESTIÓN DE CONTRATOS");

        jLabel2.setText("Documento:");

        btnBuscar.setText("Buscar Trabajador");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        jLabel3.setText("Trabajador:");

        txtTrabajador.setEditable(false);

        jLabel4.setText("Código contrato:");

        txtCodigoContrato.setEditable(false);

        jLabel5.setText("Fecha inicio:");

        txtFechaInicio.setEditable(false);

        jLabel6.setText("Fecha Fin:");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        btnConsultar.setText("Cargar contrato");
        btnConsultar.addActionListener(this::btnConsultarActionPerformed);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(422, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(126, 126, 126)
                            .addComponent(jLabel1)
                            .addGap(104, 104, 104))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBuscar))
                                .addComponent(txtTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultar)
                        .addGap(83, 83, 83)
                        .addComponent(btnActualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnLimpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar)))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCodigoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnConsultar)
                    .addComponent(btnActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCerrar))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String documento = txtDocumento.getText().trim();

        if (documento.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese el número de documento."
            );

            txtDocumento.requestFocus();

            return;
        }

        ContratoDAO contratoDAO = new ContratoDAO();

        Object[] trabajador =
                contratoDAO.buscarTrabajadorPorDocumento(documento);

        if (trabajador == null) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "No se encontró un trabajador activo con ese documento."
            );

            txtTrabajador.setText("");

            return;
        }

        txtTrabajador.setText(
                trabajador[3].toString()
                + " - "
                + trabajador[4].toString()
        );
        txtFechaInicio.setText(
        trabajador[5].toString()
        );
        ContratoDAO dao = new ContratoDAO();
        txtCodigoContrato.setText(
                dao.generarSiguienteCodigo()
        );
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String documento = txtDocumento.getText().trim();
        String trabajador = txtTrabajador.getText().trim();
        String codigoContrato = txtCodigoContrato.getText().trim();
        String fechaInicio = txtFechaInicio.getText().trim();
        String fechaFin = txtFechaFin.getText().trim();


        // 1. DOCUMENTO

        if (documento.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese y busque el documento del trabajador."
            );

            txtDocumento.requestFocus();

            return;
        }


        // 2. TRABAJADOR ENCONTRADO

        if (trabajador.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Primero debe buscar un trabajador válido."
            );

            return;
        }


        // 3. CÓDIGO DE CONTRATO

        if (codigoContrato.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese el código del contrato."
            );

            txtCodigoContrato.requestFocus();

            return;
        }


        // 4. FECHA DE INICIO

        if (fechaInicio.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese la fecha de inicio."
            );

            txtFechaInicio.requestFocus();

            return;
        }


        // 5. FECHA DE FIN

        if (fechaFin.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese la fecha de fin."
            );

            txtFechaFin.requestFocus();

            return;
        }


        // REGISTRAR CONTRATO

        ContratoDAO contratoDAO = new ContratoDAO();

        try {

            boolean registrado =
                    contratoDAO.registrar(
                            documento,
                            codigoContrato,
                            fechaInicio,
                            fechaFin
                    );

            if (registrado) {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Contrato registrado correctamente."
                );

            } else {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "No se pudo registrar el contrato.\n"
                        + "Verifique que el código no esté duplicado "
                        + "y que el trabajador no tenga ya un contrato.",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                );
            }

        } catch (IllegalArgumentException e) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Error: " + e.getMessage()
            );
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
                // TODO add your handling code here:
        String documento =
                txtDocumento.getText().trim();

        if (documento.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese el documento del trabajador."
            );

            txtDocumento.requestFocus();

            return;
        }

        ContratoDAO contratoDAO =
                new ContratoDAO();

        Object[] contrato =
                contratoDAO.consultarPorDocumento(documento);

        if (contrato == null) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "El trabajador no tiene un contrato registrado."
            );

            return;
        }

        txtCodigoContrato.setText(
                contrato[0].toString()
        );

        txtFechaInicio.setText(
                contrato[1].toString()
        );

        txtFechaFin.setText(
                contrato[2].toString()
        );

        txtTrabajador.setText(
                contrato[4].toString()
                + " - "
                + contrato[5].toString()
        );
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
                // TODO add your handling code here:
                String documento =
                txtDocumento.getText().trim();

        String nuevaFechaFin =
                txtFechaFin.getText().trim();


        if (documento.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese el documento del trabajador."
            );

            txtDocumento.requestFocus();

            return;
        }


        if (txtCodigoContrato.getText().trim().isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Primero cargue el contrato que desea actualizar."
            );

            return;
        }


        if (nuevaFechaFin.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese la nueva fecha de fin."
            );

            txtFechaFin.requestFocus();

            return;
        }


        ContratoDAO contratoDAO =
                new ContratoDAO();

        try {

            boolean actualizado =
                    contratoDAO.actualizarFechaFin(
                            documento,
                            nuevaFechaFin
                    );

            if (actualizado) {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Fecha de fin actualizada correctamente."
                );

            } else {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "No se pudo actualizar el contrato."
                );
            }

        } catch (IllegalArgumentException e) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Error: " + e.getMessage()
            );
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtDocumento.setText("");
        txtTrabajador.setText("");
        txtCodigoContrato.setText("");
        txtFechaInicio.setText("");
        txtFechaFin.setText("");

        txtDocumento.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmGestionContratos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCodigoContrato;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtTrabajador;
    // End of variables declaration//GEN-END:variables
}
