/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemapersonalmunicipal.view;

import com.mycompany.sistemapersonalmunicipal.dao.AreaDAO;

/**
 *
 * @author marantonio55
 */
public class FrmGestionAreas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmGestionAreas.class.getName());

    /**
     * Creates new form FrmGestionAreas
     */
    public FrmGestionAreas() {
        initComponents();
        setDefaultCloseOperation(
        javax.swing.WindowConstants.DISPOSE_ON_CLOSE
        )       ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoArea = new javax.swing.JTextField();
        txtNombreArea = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaListado = new javax.swing.JTextArea();
        btnCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDesactivar = new javax.swing.JButton();
        btnListarTodos = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnReactivar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("GESTION DE AREAS");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        btnBuscar.setText("Buscar ");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        txtAreaListado.setColumns(20);
        txtAreaListado.setRows(5);
        jScrollPane1.setViewportView(txtAreaListado);

        btnCerrar.setText("Cerrar ");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        jLabel2.setText("Código:");

        jLabel3.setText("Nombre: ");

        btnDesactivar.setText("Desactivar");
        btnDesactivar.addActionListener(this::btnDesactivarActionPerformed);

        btnListarTodos.setText("Listar Todos");
        btnListarTodos.addActionListener(this::btnListarTodosActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnReactivar.setText("Reactivar");
        btnReactivar.addActionListener(this::btnReactivarActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(226, 226, 226)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCodigoArea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscar))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(txtNombreArea, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnActualizar))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(btnListarTodos)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(btnDesactivar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReactivar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(67, 67, 67))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnBuscar)
                    .addComponent(btnRegistrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnActualizar)
                    .addComponent(btnDesactivar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarTodos)
                    .addComponent(btnReactivar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnLimpiar))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigoArea.getText().trim();
        String nombre = txtNombreArea.getText().trim();

        if (codigo.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese el código del área."
            );

            return;
        }

        if (nombre.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese el nombre del área."
            );

            return;
        }

        AreaDAO areaDAO = new AreaDAO();

        boolean registrado = areaDAO.insertar(
                codigo,
                nombre
        );

        if (registrado) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Área registrada correctamente."
            );

            txtCodigoArea.setText("");
            txtNombreArea.setText("");

        } else {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "No se pudo registrar el área.\n"
                    + "Verifique que el código no esté duplicado.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
   
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
            String codigo = txtCodigoArea.getText().trim();

        if (codigo.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese el código del área."
            );

            return;
        }

        AreaDAO areaDAO = new AreaDAO();

        Object[] area =
                areaDAO.buscarPorCodigo(codigo);

        if (area == null) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "No se encontró un área activa con ese código."
            );

            txtNombreArea.setText("");

        } else {

            txtCodigoArea.setText(
                    area[1].toString()
            );

            txtNombreArea.setText(
                    area[2].toString()
            );

            txtAreaListado.setText(
                    "ÁREA ENCONTRADA\n"
                    + "====================================\n\n"
                    + "ID: " + area[0] + "\n"
                    + "Código: " + area[1] + "\n"
                    + "Nombre: " + area[2]
            );
        }
    
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
      String codigo = txtCodigoArea.getText().trim();
      String nombre = txtNombreArea.getText().trim();

      if (codigo.isEmpty()) {

          javax.swing.JOptionPane.showMessageDialog(
                  this,
                  "Primero busque o ingrese el código del área."
          );

          return;
      }

      if (nombre.isEmpty()) {

          javax.swing.JOptionPane.showMessageDialog(
                  this,
                  "El nombre del área no puede estar vacío."
          );

          return;
      }

      AreaDAO areaDAO = new AreaDAO();

      boolean actualizado = areaDAO.actualizar(
              codigo,
              nombre
      );

      if (actualizado) {

          javax.swing.JOptionPane.showMessageDialog(
                  this,
                  "Área actualizada correctamente."
          );

      } else {

          javax.swing.JOptionPane.showMessageDialog(
                  this,
                  "No se pudo actualizar el área."
          );
      }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarActionPerformed
        // TODO add your handling code here:
            String codigo = txtCodigoArea.getText().trim();

        if (codigo.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Primero busque o ingrese el código del área."
            );

            return;
        }

        int respuesta =
                javax.swing.JOptionPane.showConfirmDialog(
                        this,
                        "¿Está seguro de desactivar esta área?",
                        "Confirmar desactivación",
                        javax.swing.JOptionPane.YES_NO_OPTION
                );

        if (respuesta == javax.swing.JOptionPane.YES_OPTION) {

            AreaDAO areaDAO = new AreaDAO();

            boolean desactivada =
                    areaDAO.desactivar(codigo);

            if (desactivada) {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Área desactivada correctamente."
                );

                txtCodigoArea.setText("");
                txtNombreArea.setText("");
                txtAreaListado.setText("");

            } else {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "No se pudo desactivar el área."
                );
            }
        }
       
    }//GEN-LAST:event_btnDesactivarActionPerformed

    private void btnListarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarTodosActionPerformed
                // TODO add your handling code here:
        AreaDAO areaDAO = new AreaDAO();

        java.util.List<Object[]> lista =
                areaDAO.listarTodas();

        if (lista.isEmpty()) {

            txtAreaListado.setText(
                    "No hay áreas activas registradas."
            );

            return;
        }

        StringBuilder texto = new StringBuilder();

        texto.append("LISTADO DE ÁREAS\n");
        texto.append("====================================\n\n");

        for (Object[] fila : lista) {

            texto.append("ID: ")
                    .append(fila[0])
                    .append("\n");

            texto.append("Código: ")
                    .append(fila[1])
                    .append("\n");

            texto.append("Nombre: ")
                    .append(fila[2])
                    .append("\n");

            texto.append("------------------------------------\n\n");
        }

        txtAreaListado.setText(texto.toString());
    }//GEN-LAST:event_btnListarTodosActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtCodigoArea.setText("");
        txtNombreArea.setText("");
        txtAreaListado.setText("");

        txtCodigoArea.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnReactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReactivarActionPerformed
        // TODO add your handling code here:
    String codigo = txtCodigoArea.getText().trim();

        if (codigo.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese el código del área que desea reactivar."
            );

            return;
        }

        AreaDAO areaDAO = new AreaDAO();

        Object[] area =
                areaDAO.buscarPorCodigoIncluyendoInactivos(codigo);

        if (area == null) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "No existe un área con ese código."
            );

            return;
        }

        boolean estadoActual =
                (boolean) area[3];

        if (estadoActual) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "El área ya se encuentra activa."
            );

            return;
        }

        boolean reactivada =
                areaDAO.reactivar(codigo);

        if (reactivada) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Área reactivada correctamente."
            );

        } else {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "No se pudo reactivar el área."
            );
        }
    }//GEN-LAST:event_btnReactivarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmGestionAreas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnDesactivar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListarTodos;
    private javax.swing.JButton btnReactivar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaListado;
    private javax.swing.JTextField txtCodigoArea;
    private javax.swing.JTextField txtNombreArea;
    // End of variables declaration//GEN-END:variables
}
