/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemapersonalmunicipal.view;

import com.mycompany.sistemapersonalmunicipal.dao.TrabajadorDAO;

/**
 *
 * @author marantonio55
 */
public class FrmListarTrabajadores extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmListarTrabajadores.class.getName());

    /**
     * Creates new form FrmListarTrabajadores
     */
    public FrmListarTrabajadores() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarDocumento = new javax.swing.JTextField();
        txtBuscarNombre = new javax.swing.JTextField();
        btnBuscarDocumento = new javax.swing.JButton();
        btnBuscarNombre = new javax.swing.JButton();
        btnListarTodos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaListado = new javax.swing.JTextArea();
        btnCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("LISTA Y BUSQUEDA DE TRABAJADORES ");

        btnBuscarDocumento.setText("Buscar doc.");
        btnBuscarDocumento.addActionListener(this::btnBuscarDocumentoActionPerformed);

        btnBuscarNombre.setText("Buscar nom.");
        btnBuscarNombre.addActionListener(this::btnBuscarNombreActionPerformed);

        btnListarTodos.setText("Listar todos");
        btnListarTodos.addActionListener(this::btnListarTodosActionPerformed);

        txtAreaListado.setColumns(20);
        txtAreaListado.setRows(5);
        jScrollPane1.setViewportView(txtAreaListado);

        btnCerrar.setText("Cerrar ");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        jLabel2.setText("Buscar por documento: ");

        jLabel3.setText("Buscar por nombre:");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBuscarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                            .addComponent(txtBuscarDocumento))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscarDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarNombre))
                        .addGap(71, 71, 71))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(19, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnListarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(btnLimpiar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(67, 67, 67))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarDocumento)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarNombre)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarTodos)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarTodosActionPerformed
        // TODO add your handling code here:
        TrabajadorDAO trabajadorDAO = new TrabajadorDAO();

        java.util.List<Object[]> lista = trabajadorDAO.listarTodos();

        if (lista.isEmpty()) {

            txtAreaListado.setText(

                    "No hay trabajadores registrados en la base de datos."

            );

            return;

        }

        StringBuilder texto = new StringBuilder();

        texto.append("LISTADO DE TRABAJADORES\n");

        texto.append("============================================\n\n");

        for (Object[] fila : lista) {

            texto.append("ID: ")

                    .append(fila[0])

                    .append("\n");

            texto.append("Código: ")

                    .append(fila[1])

                    .append("\n");

            texto.append("Documento: ")

                    .append(fila[2])

                    .append("\n");

            texto.append("Nombre: ")

                    .append(fila[3])

                    .append("\n");

            texto.append("Tipo: ")

                    .append(fila[4])

                    .append("\n");

            texto.append("Área: ")

                    .append(fila[5])

                    .append("\n");

            texto.append("Cargo: ")

                    .append(fila[6])

                    .append("\n");

            texto.append("Sueldo calculado: S/ ")

                    .append(fila[7])

                    .append("\n");

            texto.append("--------------------------------------------\n\n");

        }

        txtAreaListado.setText(texto.toString());   
    }//GEN-LAST:event_btnListarTodosActionPerformed

    private void btnBuscarDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDocumentoActionPerformed
        // TODO add your handling code here:
        String documento = txtBuscarDocumento.getText().trim();

        if (documento.isEmpty()) {

            txtAreaListado.setText(

                    "Ingrese un número de documento."

            );

            return;

        }

        TrabajadorDAO trabajadorDAO = new TrabajadorDAO();

        Object[] fila =

                trabajadorDAO.buscarPorDocumento(documento);

        if (fila == null) {

            txtAreaListado.setText(

                    "No se encontró trabajador con ese documento."

            );

        } else {

            StringBuilder texto = new StringBuilder();

            texto.append("TRABAJADOR ENCONTRADO\n");

            texto.append("============================================\n\n");

            texto.append("ID: ")

                    .append(fila[0])

                    .append("\n");

            texto.append("Código: ")

                    .append(fila[1])

                    .append("\n");

            texto.append("Documento: ")

                    .append(fila[2])

                    .append("\n");

            texto.append("Nombre: ")

                    .append(fila[3])

                    .append("\n");

            texto.append("Tipo: ")

                    .append(fila[4])

                    .append("\n");

            texto.append("Área: ")

                    .append(fila[5])

                    .append("\n");

            texto.append("Cargo: ")

                    .append(fila[6])

                    .append("\n");

            texto.append("Sueldo calculado: S/ ")

                    .append(fila[7])

                    .append("\n");

            txtAreaListado.setText(texto.toString());

        }
    }//GEN-LAST:event_btnBuscarDocumentoActionPerformed

    private void btnBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNombreActionPerformed
        // TODO add your handling code here:
        String nombre = txtBuscarNombre.getText().trim();

       if (nombre.isEmpty()) {

           txtAreaListado.setText(

                   "Ingrese un nombre o apellido para buscar."

           );

           return;

       }

       TrabajadorDAO trabajadorDAO = new TrabajadorDAO();

       java.util.List<Object[]> lista =

               trabajadorDAO.buscarPorNombre(nombre);

       if (lista.isEmpty()) {

           txtAreaListado.setText(

                   "No se encontraron trabajadores con ese nombre."

           );

           return;

       }

       StringBuilder texto = new StringBuilder();

       texto.append("RESULTADOS DE BÚSQUEDA\n");

       texto.append("============================================\n\n");

       for (Object[] fila : lista) {

           texto.append("ID: ")

                   .append(fila[0])

                   .append("\n");

           texto.append("Código: ")

                   .append(fila[1])

                   .append("\n");

           texto.append("Documento: ")

                   .append(fila[2])

                   .append("\n");

           texto.append("Nombre: ")

                   .append(fila[3])

                   .append("\n");

           texto.append("Tipo: ")

                   .append(fila[4])

                   .append("\n");

           texto.append("Área: ")

                   .append(fila[5])

                   .append("\n");

           texto.append("Cargo: ")

                   .append(fila[6])

                   .append("\n");

           texto.append("Sueldo calculado: S/ ")

                   .append(fila[7])

                   .append("\n");

           texto.append("--------------------------------------------\n\n");

       }

       txtAreaListado.setText(texto.toString());
    }//GEN-LAST:event_btnBuscarNombreActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtBuscarDocumento.setText("");
        txtBuscarNombre.setText("");
        txtAreaListado.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmListarTrabajadores().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarDocumento;
    private javax.swing.JButton btnBuscarNombre;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListarTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaListado;
    private javax.swing.JTextField txtBuscarDocumento;
    private javax.swing.JTextField txtBuscarNombre;
    // End of variables declaration//GEN-END:variables
}
